spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: payment-gateway
              uri: ${SPRING_CLOUD_GATEWAY_SERVER_WEBMVC_ROUTES_0_URI:http://localhost:8081}
              predicates:
                - Path=/api/payments/**
              filters:
                - StripPrefix=2
                - PrefixPath=/v1/payments
            - id: order-gateway
              uri: ${SPRING_CLOUD_GATEWAY_SERVER_WEBMVC_ROUTES_1_URI:http://localhost:8082}
              predicates:
                - Path=/api/orders/**
              filters:
                - StripPrefix=2
                - PrefixPath=/v1/orders

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 500ms
      connect-timeout: 500ms

management:
  server:
    port: 9091

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway

  observations:
    annotations:
      enabled: true

  endpoint:
    prometheus:
      enabled: true

    metrics:
      enabled: true

    gateway:
      enabled: true

rate-limiter:
  max-tokens: 100
  refill-tokens-per-second: 10
  lease-size: 10
  ttl-seconds: 7200
